// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsW3EkJE80ktFxRmlFVzh6b8xOsksrIuI',
    appId: '1:101085774174:web:08a5e343a496a065b74fcf',
    messagingSenderId: '101085774174',
    projectId: 'vazifa9-a8ad5',
    authDomain: 'vazifa9-a8ad5.firebaseapp.com',
    storageBucket: 'vazifa9-a8ad5.appspot.com',
    measurementId: 'G-SV1HTWCF0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARPNSMnkvFDmUYqZ_eE2lN106Z9tsV0AY',
    appId: '1:101085774174:android:1a37a6ce41e62d74b74fcf',
    messagingSenderId: '101085774174',
    projectId: 'vazifa9-a8ad5',
    storageBucket: 'vazifa9-a8ad5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUfwOuYHquPbQidy20Py58yxBDxuO-BGc',
    appId: '1:101085774174:ios:205bb5a8bce447d6b74fcf',
    messagingSenderId: '101085774174',
    projectId: 'vazifa9-a8ad5',
    storageBucket: 'vazifa9-a8ad5.appspot.com',
    iosBundleId: 'com.example.vazifa9Notifcations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUfwOuYHquPbQidy20Py58yxBDxuO-BGc',
    appId: '1:101085774174:ios:205bb5a8bce447d6b74fcf',
    messagingSenderId: '101085774174',
    projectId: 'vazifa9-a8ad5',
    storageBucket: 'vazifa9-a8ad5.appspot.com',
    iosBundleId: 'com.example.vazifa9Notifcations',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsW3EkJE80ktFxRmlFVzh6b8xOsksrIuI',
    appId: '1:101085774174:web:b833125e5608e367b74fcf',
    messagingSenderId: '101085774174',
    projectId: 'vazifa9-a8ad5',
    authDomain: 'vazifa9-a8ad5.firebaseapp.com',
    storageBucket: 'vazifa9-a8ad5.appspot.com',
    measurementId: 'G-8Y95Q8L59V',
  );
}
